---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
category: "categories"
baseURL: "http://khia.github.io/blog"
title: "KHIA's personal Blog"
params:
  SiteTitle: "khia.github.io"
  Author:
    Name: "ILYA Khlopotov"
    Nick: "KHIA"
    Github1: "iilyak"
    Github2: "khia"
    LinkedIn: "https://www.linkedin.com/in/iilyak"
...
