---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
indexes:
category: "categories"
baseurl: "http://khia.github.io"
title: "KHIA's personal Blog"
params:
  Site: "khia.github.io"
  Author:
    Name: "ILYA Khlopotov"
    Nick: "KHIA"
    Github: "khia"
    LinkedIn: "http://ca.linkedin.com/pub/ilya-khlopotov/b/987/265/"
...
